# Configuration for the Bio-Inspired Continual Learning Experiment
experiment:
  name: "BICL_Comprehensive_Analysis"
  seed: 42
  num_runs: 5
  methods_to_run: ['vanilla', 'unified', 'ewc']

data:
  num_tasks: 5
  n_samples_per_task: 2000
  task_difficulty: 'progressive'

model:
  input_size: 100
  hidden_sizes: [256, 128]
  num_classes: 10
  dropout_rate: 0.3

training:
  epochs: 80
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.0001
  gradient_clip_norm: 1.0
  early_stopping:
    enabled: true
    patience: 15

frameworks:
  ewc:
    lambda: 1000.0
  unified:
    beta_values: [0.1, 0.5, 1.0, 2.0, 5.0]
    divergence_type: 'adaptive'
    memory_buffer_size: 1000
    replay_ratio: 0.3